### ISSUE TITLE
1.1.1 release corrupts Gemfile.lock on MRI

### ISSUE THREAD

**Issue by dueckes** [djberg96/sys-proctable#52] opened 2016-07-13 12:39 UTC
A `bundle update` on a Gemfile containing:

```
source 'http://rubygems.org'

gem 'sys-proctable', '1.1.1'
```

Results in:
```
$ bundle update
Fetching gem metadata from http://rubygems.org/
Fetching version metadata from http://rubygems.org/
Resolving dependencies...
Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES section: 'ffi'
```

This issue also occurs for version 1.1.0.  It does not occur on version 1.0.0.

This issue may provide some insights:
https://github.com/bundler/bundler/issues/4467

**Comment by djberg96** [comment] 2016-07-13 12:50
@dueckes I'm not sure what's up, but I don't think my gem is the cause. Someone else posted about a dependency isssue recently: https://github.com/djberg96/sys-proctable/issues/51

What does `gem dependency sys-proctable` show?

**Comment by dueckes** [comment] 2016-07-17 23:34
@djberg96 Dependency list is as follows:
```
$ gem dependency sys-proctable
Gem sys-proctable-1.0.0-universal-darwin
  rake (>= 0, development)
  test-unit (>= 0, development)

Gem sys-proctable-1.1.1-universal-darwin
  ffi (>= 0)
  rake (>= 0, development)
  test-unit (>= 0, development)
```

**Comment by djberg96** [comment] 2016-07-18 00:05
@dueckes I suspect this is an issue with bundler and platform handling. What happens if you uninstall the older version?

**Comment by dueckes** [comment] 2016-07-18 00:42
Tried uninstalling all versions.  Same result.

**Comment by djberg96** [comment] 2016-07-18 12:42
@dueckes As of 1.1.0, the darwin gem has a dependency on FFI, yes.

**Comment by djberg96** [comment] 2016-07-19 14:21
@dueckes Going to close this issue, as I think this one falls on bundler and/or ffi.

**Closed by djberg96** 2016-07-19 14:21 UTC
